### ISSUE TITLE
inject does not work in dialogs

### ISSUE THREAD

**Issue by vojvodics** [Unleash/proxy-client-vue#11]
### Describe the bug

When accessing useFlag in dialogs (I am using quasar dialog), I get the following error:
![Screenshot 2022-11-23 at 19 29 53](https://user-images.githubusercontent.com/20173051/203621910-acfdee50-55dd-483d-b7ce-5d7e0e27d55f.png)

This happens because the values are provided from the root component.

The solution would be - not to use root level component for providing values, but install as a vue plugin. 

I can make a PR for the implementation if you want me to - just note that this would be a breaking change

**Comment by sighphyre** [comment]
@vojvodics We'll take a look over the related PR and give you some feedback. Thanks for the bug report and code!

**Comment by nunogois** [comment]
Hi @vojvodics, 

I tried reproducing the issue you described with no luck:
https://github.com/nunogois/quasar-issue-11
Live demo: https://quasar-issue-11-j6gantfsq-nunogois.vercel.app/#/

Could you please describe your use case to see how it differs? A demo like the one I linked or steps to reproduce the bug would be great!

Thanks 🙂

**Comment by vojvodics** [comment]
@nunogois @sighphyre Thanks for the quick feedback!

@nunogois Sorry, my description wasn't clear enough, this happens when you use a dialog plugin. I updated the reproduction example: https://github.com/nunogois/quasar-issue-11/pull/1
Live demo: https://quasar-issue-11-git-fork-vojvodics-main-nunogois.vercel.app/#/

**Comment by nunogois** [comment]
Thanks @vojvodics, this is great and definitely gives us a better understanding of the issue. I agree that a plugin could be a good solution to this issue in order to provide this capability app-wide, even outside components.
