### ISSUE TITLE
Could not find a declaration file for module '@unleash/proxy-client-vue'

### ISSUE THREAD

**Issue by Ked57** [Unleash/proxy-client-vue#27]
### Describe the bug

When I use the package in a vue + typescript + vite application with `"type": "module"` I get the error

> Could not find a declaration file for module '@unleash/proxy-client-vue'. '.../node_modules/.pnpm/@unleash+proxy-client-vue@0.1.0_typescript@5.4.5/node_modules/@unleash/proxy-client-vue/dist/index.es.js' implicitly has an 'any' type.
  There are types at '.../node_modules/@unleash/proxy-client-vue/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@unleash/proxy-client-vue' library may need to update its package.json or typings.ts(7016)

### Steps to reproduce the bug

1. Install the package in a vue + typescript + vite application with `"type": "module"`
2. When importing the unleash plugin
3. Typescript should throw an error as shown above

### Expected behavior

No error from typescript

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

0.1.0

**Comment by andreas-unleash** [comment]
Hi @Ked57 , thanks for bringing this in. I will run it by the team and get back to you

**Comment by Ked57** [comment]
Hi, I opened a PR with a potential fix 😄 thank you

**Comment by andreas-unleash** [comment]
Hi @Ked57 , we just released v0.1.1 with your fix.  Thank you for contributing!

**Comment by Ked57** [comment]
thank you !
