### ISSUE TITLE
Default condition should be last one

### ISSUE THREAD

**Issue by feifeiteacher** [Unleash/proxy-client-vue#30]
### Describe the bug

Using this dependency in projects with vue3.0.0 and webpack will cause the project build to fail

### Steps to reproduce the bug

1.npm install @unleash/proxy-client-vue
2.import { useFlag } from '@unleash/proxy-client-vue'
3.const isEnabled = useFlag('test-toggle')

### Unleash version

0.1.1

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by nunogois** [comment]
Hi @feifeiteacher, thank you for opening this issue. This should be fixed in the latest v0.1.2. Can you please confirm?

**Comment by feifeiteacher** [comment]
When will version 0.1.2 be available online

**Comment by nunogois** [comment]
Hi @feifeiteacher, version 0.1.2 has been released ~3 hours ago: https://github.com/Unleash/proxy-client-vue/releases/tag/v0.1.2
