### ISSUE TITLE
Types generated by rollup-plugin-typescript2 are wrong

### ISSUE THREAD

**Issue by hidde-jan** [Unleash/proxy-client-vue#9]
### Describe the bug

The `rollup-plugin-typescript2` plugin for vite generates types (d.ts files) that have wrong types in them, compared to when you use `tsc` or `vue-tsc` to emit types.

With rollup plugin:
```typescript
# useFlag.d.ts
declare const useFlag: (name: any) => import("vue").Ref<boolean>;
export default useFlag;
```

With tsc/vue-tsc:
```typescript
declare const useFlag: (name: string) => import("vue").Ref<boolean>;
export default useFlag;
```

The plugin outputs `any` in multiple places.

### Steps to reproduce the bug

Run `yarn build` and check the `dist` folder for d.ts files.

Run `yarn run tsc --emitDeclarationOnly` and check the `dist` folder for d.ts files.

### Expected behavior

The build output should have types that are derived correctly from the typescript source.

**Comment by nunogois** [comment]
Hey @hidde-jan - Thanks for pointing this out! Would something like https://github.com/Unleash/proxy-client-vue/pull/10 help?
